version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: deepseek-db
    environment:
      POSTGRES_DB: deepseek_messenger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - deepseek-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: deepseek-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - deepseek-network
    command: redis-server --appendonly yes

  # Backend API server
  backend:
    build: ./backend
    container_name: deepseek-backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: deepseek_messenger
      DB_USER: postgres
      DB_PASSWORD: your_secure_password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: your_jwt_secret_key_here
      S3_BUCKET: your-s3-bucket
      S3_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - deepseek-network
    restart: unless-stopped

  # WebRTC signaling server
  webrtc:
    build: ./webrtc-server
    container_name: deepseek-webrtc
    ports:
      - "5001:5001"
    networks:
      - deepseek-network
    restart: unless-stopped

  # Frontend (React app)
  frontend:
    build: ./frontend
    container_name: deepseek-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:5000
      REACT_APP_WS_URL: ws://localhost:5000
      REACT_APP_WEBRTC_URL: ws://localhost:5001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - deepseek-network
    restart: unless-stopped

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: deepseek-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/cert.pem:/etc/ssl/cert.pem
      - ./ssl/key.pem:/etc/ssl/key.pem
    depends_on:
      - frontend
      - backend
      - webrtc
    networks:
      - deepseek-network
    restart: unless-stopped

  # TURN server (for WebRTC in production)
  coturn:
    image: coturn/coturn:latest
    container_name: deepseek-turn
    environment:
      - TURN_SECRET=your_turn_secret
      - REALM=deepseek.com
      - MIN_PORT=49152
      - MAX_PORT=65535
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "49152-65535:49152-65535/udp"
    networks:
      - deepseek-network
    command: |
      turnserver --verbose \
      --lt-cred-mech \
      --fingerprint \
      --use-auth-secret \
      --static-auth-secret=${TURN_SECRET} \
      --realm=${REALM} \
      --external-ip=${EXTERNAL_IP} \
      --min-port=${MIN_PORT} \
      --max-port=${MAX_PORT} \
      --no-tls \
      --no-dtls

volumes:
  postgres_data:
  redis_data:

networks:
  deepseek-network:
    driver: bridge